### ISSUE TITLE
[Issue]: MAD_MODEL_NAME no longer supported

### ISSUE THREAD

**Issue by coleramos425** [ROCm/MAD#11]
### Problem Description

I tried specifying a target model using `MAD_MODEL_NAME`, however, in the latest version it appears this env variable is no longer supported.
https://github.com/ROCm/MAD/commit/e744d4c5fecf33c985caa7948241f2919c5e7976

I suggest you remove mention of `MAD_MODEL_NAME` from your README since `--tags` is no the preferred method of targeting a specific model

### Operating System

Rocky Linux 9.4

### CPU

AMD EPYC 7V13 64-Core Processor

### GPU

AMD Instinct MI250

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

```shell
git clone https://github.com/coleramos425/MAD.git
export MAD_MODEL_NAME=pyt_huggingface_gpt2
python3 tools/run_models.py --live-output


/home1/colramos/mad-fork/tools/utils.py:944: SyntaxWarning: invalid escape sequence '\d'
  perf_regex = ".*performance:\\s*([+|-]?\d*[.]?\d*)\\s*.*\\s*"
/home1/colramos/mad-fork/tools/utils.py:946: SyntaxWarning: invalid escape sequence '\d'
  metric_regex = ".*performance:\\s*[+|-]?\d*[.]?\d*\\s*(\w*)\\s*"
Traceback (most recent call last):
  File "/home1/colramos/mad-fork/tools/run_models.py", line 494, in <module>
    sys.exit(main() == False)
             ^^^^^^
  File "/home1/colramos/mad-fork/tools/run_models.py", line 480, in main
    with open('tags.json') as t:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'tags.json'
```

**Comment by coketaste** [comment]
MAD_MODEL_NAME is an env variable for docker cmd. It is not used with python3 tools/run_models.py. Please use the following line to run your model as reference.
python3 tools/run_models.py --tags pyt_huggingface_gpt2 --live-output
